CREATE TABLE CAFE_INFO (
   CAFE_CODE VARCHAR2(20),
   NAME VARCHAR2(100),
   URL VARCHAR2(100),
   IMG_PATH VARCHAR2(100)
);


CREATE TABLE CAFE_ATTR
   (   "CAFE_CODE" VARCHAR2(20), 
   "COL1" NUMBER, 
   "COL2" NUMBER, 
   "COL3" NUMBER, 
   "COL4" NUMBER, 
   "COL5" NUMBER, 
   "COL6" NUMBER, 
   "COL7" NUMBER, 
   "COL8" NUMBER, 
   "COL9" NUMBER, 
   "COL10" NUMBER,
   "COL11" NUMBER,
   "COL12" NUMBER,
   "COL13" NUMBER,
   "COL14" NUMBER,
   "COL15" NUMBER,
);

CREATE TABLE SELECTED_WEIGHT (
   SURVEY_CODE VARCHAR2(100),
   BEST1 VARCHAR2(100),
   BEST2 VARCHAR2(100),
   BEST3 VARCHAR2(100)
);

CREATE TABLE servey_result (
   SERVEY_CODE VARCHAR2(100),
   "result" VARCHAR2(100)
);


CREATE TABLE CAFE_CLASSIFICATION (
   CAFE_CODE VARCHAR2(100),
   CLASSIFICATION INTEGER
);

CREATE TABLE SERVEY_ATTR (
   SERVEY_CODE VARCHAR2(100),
   COL1 INTEGER,
   COL2 INTEGER,
   COL3 INTEGER,
   COL4 INTEGER,
   COL5 INTEGER,
   COL6 INTEGER,
   COL7 INTEGER,
   COL8 INTEGER,
   COL9 INTEGER,
   COL10 INTEGER
);