
drop table CAFE_INFO;
drop table cafe_attr;
CREATE TABLE CAFE_INFO (
   CAFE_CODE VARCHAR2(20),
   NAME VARCHAR2(100),
   URL VARCHAR2(400),
   IMG_NAME VARCHAR2(100)
);
CREATE TABLE cafe_attr(
   CAFE_CODE VARCHAR2(20),
   ATTR VARCHAR2(100),
   QUANTITY NUMBER
);
CREATE TABLE SELECTED_WEIGHT (
   SURVEY_CODE VARCHAR2(100),
   BEST1 VARCHAR2(100),
   BEST2 VARCHAR2(100),
   BEST3 VARCHAR2(100)
);

CREATE TABLE servey_result (
   SERVEY_CODE VARCHAR2(100),
   "result" VARCHAR2(100)
);


CREATE TABLE CAFE_CLASSIFICATION (
   CAFE_CODE VARCHAR2(100),
   CLASSIFICATION INTEGER
);

CREATE TABLE SERVEY_ATTR (
   SERVEY_CODE VARCHAR2(100),
   COL1 INTEGER,
   COL2 INTEGER,
   COL3 INTEGER,
   COL4 INTEGER,
   COL5 INTEGER,
   COL6 INTEGER,
   COL7 INTEGER,
   COL8 INTEGER,
   COL9 INTEGER,
   COL10 INTEGER
);
