;
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('116','카페봄날.jpg','카페봄날','https://map.naver.com/v5/entry/place/37414260?c=14223708.6531636,4563979.6935178,14,0,0,0,dh&placePath=%2Fphoto%3F');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('117','LATARTA.jpeg','LATARTA','https://map.naver.com/v5/search/LATARTA/place/1646935677?c=14223708.6531636,4563979.6935178,14,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('118','산토리니.jpg','산토리니','https://map.naver.com/v5/search/%EC%82%B0%ED%86%A0%EB%A6%AC%EB%8B%88/place/11821473?c=14223083.5496950,4564090.7335932,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('119','투썸플레이스춘천구봉산점.jpg','투썸플레이스춘천구봉산점','https://map.naver.com/v5/search/%ED%88%AC%EC%8D%B8%ED%94%8C%EB%A0%88%EC%9D%B4%EC%8A%A4%EC%B6%98%EC%B2%9C%EA%B5%AC%EB%B4%89%EC%82%B0%EC%A0%90/place/36316360?c=14223076.8593936,4564220.6486031,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('120','곤트란쉐리에 지씨아뜰리에.jpg','곤트란쉐리에 지씨아뜰리에','https://map.naver.com/v5/entry/place/1064572838?c=14223972.2911137,4564321.3796984,13,0,0,0,dh&placePath=%2Fhome%3Fentry=plt');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('121','쿠폴라.jpg','쿠폴라','https://map.naver.com/v5/search/%EC%BF%A0%ED%8F%B4%EB%9D%BC/place/35101367?c=14223581.9270553,4564320.6179696,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('122','스카이블루.jpg','스카이블루','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%8A%A4%EC%B9%B4%EC%9D%B4%EB%B8%94%EB%A3%A8/place/1958168420?c=14223157.5103647,4564389.2019974,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('123','파미르.jpeg','파미르','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%ED%8C%8C%EB%AF%B8%EB%A5%B4/place/1883720159?c=14223843.6725740,4564621.0255711,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('124','신북커피.jpeg','신북커피','https://map.naver.com/v5/entry/place/1918874636?c=14222407.8403859,4569488.3716190,13,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('125','막싸도라의 커피여행.jpeg','막싸도라의 커피여행','https://map.naver.com/v5/search/%EB%A7%89%EC%8B%B8%EB%8F%84%EB%9D%BC%EC%9D%98%20%EC%BB%A4%ED%94%BC%EC%97%AC%ED%96%89/place/808665064?c=14224409.6208652,4569483.1356556,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('126','이디야 춘천소양강점.jpeg','이디야 춘천소양강점','https://map.naver.com/v5/search/%EC%9D%B4%EB%94%94%EC%95%BC%20%EC%B6%98%EC%B2%9C%EC%86%8C%EC%96%91%EA%B0%95%EC%A0%90/place/1625998870?c=14223787.4896270,4569558.0624030,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('127','감자밭.jpeg','감자밭','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EA%B0%90%EC%9E%90%EB%B0%AD/place/1823037411?c=14224439.5212804,4569487.1861176,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('128','맘인더가든 샘밭점.jpeg','맘인더가든 샘밭점','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EB%A7%98%EC%9D%B8%EB%8D%94%EA%B0%80%EB%93%A0%20%EC%83%98%EB%B0%AD%EC%A0%90/place/1685348926?c=14224588.7895856,4569500.4665635,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('129','카페나스.jpeg','카페나스','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%B9%B4%ED%8E%98%EB%82%98%EC%8A%A4/place/31970079?c=14224588.7895856,4569500.4665635,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('130','레미니센스 소양.jpeg','레미니센스 소양','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EB%A0%88%EB%AF%B8%EB%8B%88%EC%84%BC%EC%8A%A4%20%EC%86%8C%EC%96%91/place/1312220408?c=14224588.7895856,4569500.4665635,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('131','소소록.jpeg','소소록','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%86%8C%EC%86%8C%EB%A1%9D/place/1530800029?c=14225460.7885529,4570018.1772786,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('132','투썸플레이스 춘천소양강댐점.jpeg','투썸플레이스 춘천소양강댐점','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%ED%88%AC%EC%8D%B8%ED%94%8C%EB%A0%88%EC%9D%B4%EC%8A%A4%20%EC%B6%98%EC%B2%9C%EC%86%8C%EC%96%91%EA%B0%95%EB%8C%90%EC%A0%90/place/1755497228?c=14224865.4185202,4569860.2588001,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('133','어스17.jpeg','어스17','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%96%B4%EC%8A%A417/place/36331492?c=14225495.4757062,4569932.5207782,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('134','서면카페.jpeg','서면카페','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%84%9C%EB%A9%B4%EC%B9%B4%ED%8E%98/place/1413857266?c=14207703.2592288,4565552.4628753,12,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('135','구름빵카페.jpeg','구름빵카페','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EA%B5%AC%EB%A6%84%EB%B9%B5%EC%B9%B4%ED%8E%98/place/1272516779?c=14210879.8165583,4564358.3941428,12,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('136','빵카페 베카랜드.jpeg','빵카페 베카랜드','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EB%B9%B5%EC%B9%B4%ED%8E%98%20%EB%B2%A0%EC%B9%B4%EB%9E%9C%EB%93%9C/place/1682946673?c=14210879.8165583,4564358.3941428,12,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('137','카페카르페.jpeg','카페카르페','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%B9%B4%ED%8E%98%EC%B9%B4%EB%A5%B4%ED%8E%98/place/1461627977?c=14210879.8165583,4564358.3941428,12,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('138','이디야커피 춘천의암호점.jpeg','이디야커피 춘천의암호점','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%9D%B4%EB%94%94%EC%95%BC%EC%BB%A4%ED%94%BC%20%EC%B6%98%EC%B2%9C%EC%9D%98%EC%95%94%ED%98%B8%EC%A0%90/place/1815009947?c=14212716.3432535,4563132.6993680,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('139','Urban green.jpeg','Urban green','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20Urban%20green/place/344719512?c=14213157.1016454,4563100.3296485,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('140','올라.jpeg','올라','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%98%AC%EB%9D%BC/place/242920308?c=14216975.7831937,4562681.4505997,13,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('141','카페처방전.jpeg','카페처방전','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%B9%B4%ED%8E%98%EC%B2%98%EB%B0%A9%EC%A0%84/place/15045798?c=14216708.8056589,4562124.6309410,13,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('142','공차 춘천명동점.jpeg','공차 춘천명동점','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EA%B3%B5%EC%B0%A8/place/1932183369?c=14188633.2731083,4562364.8237194,10,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('143','메가커피 춘천명동점.jpeg','메가커피 춘천명동점','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EB%A9%94%EA%B0%80%EC%BB%A4%ED%94%BC/place/1441743128?c=14188718.5438382,4562450.1921458,10,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('114','라뜰리에 김가.jpeg','라뜰리에 김가','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EB%9D%BC%EB%9C%B0%EB%A6%AC%EC%97%90%20%EA%B9%80%EA%B0%80/place/21240709?c=14209285.3207000,4563107.5511197,10,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('115','제이콥스스테이션.jpeg','제이콥스스테이션','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%A0%9C%EC%9D%B4%EC%BD%A5%EC%8A%A4%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%85%98/place/15118854?c=14209285.3207000,4563107.5511197,10,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('144','베이크포레스트.jfif','베이크포레스트','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%EB%B2%A0%EC%9D%B4%ED%81%AC%ED%8F%AC%EB%A0%88%EC%8A%A4%ED%8A%B8/place/1889684518?c=14220449.8641262,4553987.3071142,13,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('145','크로프트.PNG','크로프트','https://map.naver.com/v5/search/%ED%81%AC%EB%A1%9C%ED%94%84%ED%8A%B8/place/89854160?c=14217523.8758385,4562190.6054812,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('146','초이랑.PNG','초이랑','https://map.naver.com/v5/entry/place/1985750744?c=14224137.1775434,4569642.3327065,15,0,0,0,dh');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('147','감성커피.jpg','감성커피 춘천명동점','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EA%B0%90%EC%84%B1%EC%BB%A4%ED%94%BC/place/1098407422?c=14203933.7141038,4562681.4505997,10,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('148','레미니센스.jfif','레미니센스 소양','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EB%A0%88%EB%AF%B8%EB%8B%88%EC%84%BC%EC%8A%A4/place/1462524633?c=14216690.2375678,4559941.0790399,15,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('149','그날의 우리.jfif','그날의 우리','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%B9%B4%ED%8E%98/place/1653666034?c=14211386.3313734,4562681.4505997,11,0,0,0,dh&placePath=%3Fentry%253Dbmp');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('150','키리엘.jfif','키리엘','https://map.naver.com/v5/search/%ED%82%A4%EB%A6%AC%EC%97%98/place/1132026779?c=14218358.4380610,4560195.1808169,15,0,0,0,dh&placePath=%3Fentry%253Dpll');
insert into cafe_info(cafe_code, IMG_NAME, name, url) values('151','분덕스.jfif','분덕스','https://map.naver.com/v5/search/%EC%B6%98%EC%B2%9C%20%EC%B9%B4%ED%8E%98/place/1980592320?c=14203933.7141038,4562681.4505997,10,0,0,0,dh&placePath=%3Fentry%253Dpll');

insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','화장실이 깨끗해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','뷰가 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','좌석이 편해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','뷰가 좋아요',17);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','커피가 맛있어요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','사진이 잘 나와요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','주차하기 편해요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','디저트가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','매장이 청결해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','좌석이 편해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','음료가 맛있어요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','친절해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','대화하기 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','인테리어가 멋져요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','화장실이 깨끗해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('129','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','인테리어가 멋져요',13);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','매장이 청결해요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','친절해요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','디저트가 맛있어요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','커피가 맛있어요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','주차하기 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','뷰가 좋아요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','음료가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','사진이 잘 나와요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','대화하기 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','좌석이 편해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','화장실이 깨끗해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('130','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','매장이 청결해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','음료가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','커피가 맛있어요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','인테리어가 멋져요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','사진이 잘 나와요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','대화하기 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','뷰가 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','화장실이 깨끗해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','친절해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','주차하기 편해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','가성비가 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('131','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','매장이 청결해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','친절해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','음료가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','커피가 맛있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','좌석이 편해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','디저트가 맛있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','주차하기 편해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','인테리어가 멋져요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','대화하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('132','뷰가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','뷰가 좋아요',47);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','주차하기 편해요',17);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','좌석이 편해요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','커피가 맛있어요',13);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','인테리어가 멋져요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','매장이 청결해요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','사진이 잘 나와요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','대화하기 좋아요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','음료가 맛있어요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','친절해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','특별한 메뉴가 있어요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','화장실이 깨끗해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','디저트가 맛있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('133','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','"뷰가 좋아요"',22);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','커피가 맛있어요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','음료가 맛있어요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','인테리어가 멋져요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','친절해요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','디저트가 맛있어요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','사진이 잘 나와요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','매장이 청결해요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','좌석이 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','주차하기 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','대화하기 좋아요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','화장실이 깨끗해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','가성비가 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('134','집중하기 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','뷰가 좋아요',20);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','좌석이 편해요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','음료가 맛있어요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','사진이 잘 나와요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','매장이 청결해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','주차하기 편해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','디저트가 맛있어요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','대화하기 좋아요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','커피가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','가성비가 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','친절해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','특별한 메뉴가 있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('135','인테리어가 멋져요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','빵이 맛있어요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','친절해요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','뷰가 좋아요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','커피가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','주차하기 편해요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','좌석이 편해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','대화하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','가성비가 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','음료가 맛있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','인테리어가 멋져요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('136','화장실이 깨끗해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','뷰가 좋아요',53);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','매장이 청결해요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','사진이 잘 나와요',18);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','커피가 맛있어요',17);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','친절해요',17);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','주차하기 편해요',17);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','인테리어가 멋져요',15);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','좌석이 편해요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','음료가 맛있어요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','대화하기 좋아요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','디저트가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','화장실이 깨끗해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','가성비가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('137','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','뷰가 좋아요',25);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','커피가 맛있어요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','음료가 맛있어요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','매장이 청결해요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','좌석이 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','친절해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','주차하기 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','사진이 잘 나와요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','가성비가 좋아요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','대화하기 좋아요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','화장실이 깨끗해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','인테리어가 멋져요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','디저트가 맛있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('138','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','뷰가 좋아요',35);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','사진이 잘 나와요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','음료가 맛있어요',17);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','친절해요',16);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','주차하기 편해요',16);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','커피가 맛있어요',15);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','매장이 청결해요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','디저트가 맛있어요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','인테리어가 멋져요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','좌석이 편해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','대화하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('139','화장실이 깨끗해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','뷰가 좋아요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','사진이 잘 나와요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','커피가 맛있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','인테리어가 멋져요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','음료가 맛있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','매장이 청결해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','디저트가 맛있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','대화하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('140','화장실이 깨끗해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','특별한 메뉴가 있어요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','친절해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','음료가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','대화하기 좋아요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','커피가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','인테리어가 멋져요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','매장이 청결해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','화장실이 깨끗해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','좌석이 편해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','디저트가 맛있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','주차하기 편해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','가성비가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('141','뷰가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','음료가 맛있어요',28);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','매장이 청결해요',15);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','좌석이 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','친절해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','대화하기 좋아요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','차가 맛있어요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','사진이 잘 나와요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','가성비가 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','디저트가 맛있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('142','뷰가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('143','음료가 맛있어요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('143','가성비가 좋아요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('143','커피가 맛있어요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('143','친절해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('143','매장이 청결해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('143','인테리어가 멋져요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('143','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','디저트가 맛있어요',44);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','커피가 맛있어요',35);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','뷰가 좋아요',52);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','주차하기 편해요',49);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','인테리어가 멋져요',31);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','친절해요',28);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','대화하기 좋아요',27);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','특별한 메뉴가 있어요',21);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','빵이 맛있어요',20);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','음료가 맛있어요',20);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','매장이 청결해요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','사진이 잘 나와요',18);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','화장실이 깨끗해요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','가성비가 좋아요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','좌석이 편해요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('114','집중하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','뷰가 좋아요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','커피가 맛있어요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','매장이 청결해요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','친절해요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','주차하기 편해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','디저트가 맛있어요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','화장실이 깨끗해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','음료가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','사진이 잘 나와요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','가성비가 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','좌석이 편해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','인테리어가 멋져요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','대화하기 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('115','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','뷰가 좋아요',18);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','주차하기 편해요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','커피가 맛있어요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','사진이 잘 나와요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','디저트가 맛있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','가성비가 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','대화하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','음료가 맛있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','인테리어가 멋져요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','친절해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','매장이 청결해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('116','화장실이 깨끗해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','뷰가 좋아요',39);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','디저트가 맛있어요',22);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','커피가 맛있어요',20);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','음료가 맛있어요',16);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','주차하기 편해요',16);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','인테리어가 멋져요',13);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','매장이 청결해요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','대화하기 좋아요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','사진이 잘 나와요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','특별한 메뉴가 있어요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','좌석이 편해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','화장실이 깨끗해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','친절해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('117','가성비가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','뷰가 좋아요',149);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','사진이 잘 나와요',80);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','주차하기 편해요',54);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','인테리어가 멋져요',46);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','매장이 청결해요',37);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','커피가 맛있어요',36);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','친절해요',33);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','음료가 맛있어요',24);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','화장실이 깨끗해요',22);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','대화하기 좋아요',20);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','디저트가 맛있어요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','좌석이 편해요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','가성비가 좋아요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','특별한 메뉴가 있어요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('118','집중하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','뷰가 좋아요',68);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','주차하기 편해요',38);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','커피가 맛있어요',29);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','매장이 청결해요',27);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','디저트가 맛있어요',24);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','사진이 잘 나와요',22);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','대화하기 좋아요',20);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','인테리어가 멋져요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','좌석이 편해요',18);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','친절해요',18);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','화장실이 깨끗해요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','음료가 맛있어요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','집중하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('119','가성비가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','뷰가 좋아요',81);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','빵이 맛있어요',58);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','매장이 청결해요',35);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','인테리어가 멋져요',33);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','사진이 잘 나와요',25);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','주차하기 편해요',23);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','커피가 맛있어요',21);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','음료가 맛있어요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','좌석이 편해요',16);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','친절해요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','특별한 메뉴가 있어요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','대화하기 좋아요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','화장실이 깨끗해요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('120','가성비가 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','뷰가 좋아요',29);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','디저트가 맛있어요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','인테리어가 멋져요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','커피가 맛있어요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','친절해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','주차하기 편해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','사진이 잘 나와요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','매장이 청결해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','좌석이 편해요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','음료가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','대화하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','화장실이 깨끗해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','가성비가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('121','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','뷰가 좋아요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','친절해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','인테리어가 멋져요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','주차하기 편해요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','매장이 청결해요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','사진이 잘 나와요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','가성비가 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','집중하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','대화하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','화장실이 깨끗해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','좌석이 편해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','디저트가 맛있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('122','음료가 맛있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','뷰가 좋아요',29);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','인테리어가 멋져요',15);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','매장이 청결해요',13);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','빵이 맛있어요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','커피가 맛있어요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','친절해요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','주차하기 편해요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','사진이 잘 나와요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','좌석이 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','음료가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','대화하기 좋아요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','화장실이 깨끗해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','가성비가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('123','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','인테리어가 멋져요',150);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','커피가 맛있어요',127);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','음료가 맛있어요',106);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','주차하기 편해요',99);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','사진이 잘 나와요',96);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','특별한 메뉴가 있어요',96);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','친절해요',76);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','뷰가 좋아요',76);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','매장이 청결해요',73);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','좌석이 편해요',47);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','대화하기 좋아요',46);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','디저트가 맛있어요',35);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','화장실이 깨끗해요',22);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','가성비가 좋아요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('124','집중하기 좋아요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','커피가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','음료가 맛있어요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','인테리어가 멋져요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','친절해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','사진이 잘 나와요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','가성비가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','매장이 청결해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','대화하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','화장실이 깨끗해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('125','뷰가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','뷰가 좋아요',79);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','매장이 청결해요',66);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','주차하기 편해요',63);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','인테리어가 멋져요',57);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','가성비가 좋아요',42);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','사진이 잘 나와요',37);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','커피가 맛있어요',31);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','좌석이 편해요',30);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','친절해요',30);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','화장실이 깨끗해요',29);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','대화하기 좋아요',24);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','음료가 맛있어요',23);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','디저트가 맛있어요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','특별한 메뉴가 있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('126','집중하기 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','빵이 맛있어요',232);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','특별한 메뉴가 있어요',149);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','뷰가 좋아요',147);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','사진이 잘 나와요',110);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','주차하기 편해요',69);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','인테리어가 멋져요',63);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','친절해요',51);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','커피가 맛있어요',48);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','음료가 맛있어요',37);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','매장이 청결해요',33);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','대화하기 좋아요',18);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','화장실이 깨끗해요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','좌석이 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','가성비가 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('127','집중하기 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','커피가 맛있어요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','친절해요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','주차하기 편해요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','디저트가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','인테리어가 멋져요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','사진이 잘 나와요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','매장이 청결해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','음료가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','대화하기 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('128','특별한 메뉴가 있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','뷰가 좋아요',56);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','인테리어가 멋져요',36);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','사진이 잘 나와요',31);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','디저트가 맛있어요',21);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','커피가 맛있어요',20);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','매장이 청결해요',13);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','음료가 맛있어요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','주차하기 편해요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','친절해요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','대화하기 좋아요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','화장실이 깨끗해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','좌석이 편해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','가성비가 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('144','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('145','인테리어가 멋져요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('145','음료가 맛있어요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('145','커피가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('145','특별한 메뉴가 있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('145','사진이 잘 나와요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('145','뷰가 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('145','매장이 청결해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('145','화장실이 깨끗해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','디저트가 맛있어요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','매장이 청결해요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','사진이 잘 나와요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','음료가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','커피가 맛있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','인테리어가 멋져요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','대화하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','친절해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','좌석이 편해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','주차하기 편해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('146','화장실이 깨끗해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','가성비가 좋아요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','좌석이 편해요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','친절해요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','음료가 맛있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','매장이 청결해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','대화하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','커피가 맛있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','디저트가 맛있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('147','뷰가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','인테리어가 멋져요',13);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','매장이 청결해요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','친절해요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','디저트가 맛있어요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','커피가 맛있어요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','주차하기 편해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','뷰가 좋아요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','음료가 맛있어요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','사진이 잘 나와요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','대화하기 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','좌석이 편해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','화장실이 깨끗해요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('148','특별한 메뉴가 있어요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','매장이 청결해요',20);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','디저트가 맛있어요',16);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','인테리어가 멋져요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','특별한 메뉴가 있어요',14);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','커피가 맛있어요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','친절해요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','사진이 잘 나와요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','음료가 맛있어요',9);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','대화하기 좋아요',6);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','좌석이 편해요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','가성비가 좋아요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','주차하기 편해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','집중하기 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','화장실이 깨끗해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('149','뷰가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','친절해요',13);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','커피가 맛있어요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','음료가 맛있어요',8);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','매장이 청결해요',7);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','인테리어가 멋져요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','디저트가 맛있어요',4);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','좌석이 편해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','대화하기 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','화장실이 깨끗해요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','사진이 잘 나와요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','가성비가 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','특별한 메뉴가 있어요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','집중하기 좋아요',2);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','주차하기 편해요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('150','뷰가 좋아요',1);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','인테리어가 멋져요',38);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','주차하기 편해요',37);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','사진이 잘 나와요',32);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','뷰가 좋아요',23);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','커피가 맛있어요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','친절해요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','매장이 청결해요',19);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','디저트가 맛있어요',15);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','화장실이 깨끗해요',12);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','좌석이 편해요',11);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','음료가 맛있어요',10);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','대화하기 좋아요',5);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','가성비가 좋아요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','특별한 메뉴가 있어요',3);
insert into cafe_attr(cafe_code, attr, QUANTITY) values('151','집중하기 좋아요',2);

select ci.name as name, ci.url as url, ci.img_name as imgName
      from cafe_info ci, cafe_attr ca 
      where ci.cafe_code = ca.cafe_code 
      and ca.attr='집중하기 좋아요' 
      order by ca.quantity desc and rownum between 3;
      
      select ci.name as name, ci.url as url, ci.img_name as imgName
      from cafe_info ci, cafe_attr ca 
      where ci.cafe_code = ca.cafe_code 
      and ca.attr='집중하기 좋아요' and rownum between 1 and 3
      order by ca.quantity desc;